### ISSUE TITLE
Linkedin login issue

### ISSUE THREAD

**Issue by dehui1109** [Satish-Lakhani/ng-social-login#1]
I got the errors as following when I was going to login with Linkedin.
![screen shot 2018-05-10 at 6 40 38 am](https://user-images.githubusercontent.com/38732997/39866115-47405522-541d-11e8-9c2b-a601ad11eeb0.png)

**Comment by Satish-Lakhani** [comment]
Hi @dehui1109 ,
Thanks for reporting an issue, but sorry this doesn't seem valid, or can you please provide steps for issue reproduction?

Make sure you have done the proper configuration on linked developer console.
I've attached a working example of the plugin integration [ng-social-login-demo.zip](https://github.com/Satish-Lakhani/ng-social-login/files/2084744/ng-social-login-demo.zip). You can check/run it.

To run it, perform below steps.
1) npm install
2) Put client_id in app.module.ts, 
3) ng serve.

And you should be able to login via LinkedIn.

**Comment by RU-1109** [comment]
Okay, let me try.
And let you know the result again.

Thanks for your effort.
